# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.2.0
   hooks:
     -  id: trailing-whitespace
        files: ^Homework/Homework-6/
     -  id: end-of-file-fixer
        files: ^Homework/Homework-6/
     -  id: check-yaml
        files: ^Homework/Homework-6/
     -  id: check-added-large-files
        files: ^Homework/Homework-6/
-  repo: https://github.com/psf/black
   rev: 23.7.0
   hooks:
      -  id: black
         language_version: python3.10