# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: ^Homework/Homework-6/
    -   id: end-of-file-fixer
        files: ^Homework/Homework-6/
    -   id: check-yaml
        files: ^Homework/Homework-6/
    -   id: check-added-large-files
        files: ^Homework/Homework-6/
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
        - id: black
        language_version: python3.11
        files: ^Homework/Homework-6/
-   repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
        - id: isort
        name: isort (python)
        files: ^Homework/Homework-6/
-   repo: local
    hooks:
    -    id: pylint
         name: pylint
         entry: pylint
         language: system
         types: [python]
         args:
           [
             "-rn", # Only display messages
             "-sn", # Don't display the score
             "--recursive=y",
             "--rcfile=pylintrc",
             "--load-plugins=pylint.extensions.bad_builtin"
           ]
         files: ^Homework/Homework-6/
-   repo: local
    hooks:
        - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        files: ^Homework/Homework-6/

